export const dummyList = [
  {
    id: 1,
    status: "출석 완료",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
  {
    id: 2,
    status: "공결",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
  {
    id: 3,
    status: "출석 완료",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
  {
    id: 4,
    status: "출석 완료",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
  {
    id: 5,
    status: "출석 완료",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
  {
    id: 6,
    status: "결석",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
  {
    id: 7,
    status: "출석 완료",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
  {
    id: 8,
    status: "공결",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
  {
    id: 9,
    status: "출석 완료",
    title: "와이어 프레임 작성 회의",
    date: "2024년 3월 2일 월요일",
    time: "11:00 AM",
  },
];
